package ru.ramanpan.petroprimoweb.model.enums;

public enum DeterministicOption {
    UNDEFINED,
    EASY_MEDIUM_HARD,
    EASY_HARD_MEDIUM,
    HARD_MEDIUM_EASY,
    HARD_EASY_MEDIUM,
    MEDIUM_EASY_HARD,
    MEDIUM_HARD_EASY,
    POLITIC_CULTURE_ECONOMIC,
    POLITIC_ECONOMIC_CULTURE,
    CULTURE_ECONOMIC_POLITIC,
    CULTURE_POLITIC_ECONOMIC,
    ECONOMIC_POLITIC_CULTURE,
    ECONOMIC_CULTURE_POLITIC,
}
